import { getCentroidLatLong } from "src/app/commonFunctions/functions";
import { Country, ICountryOld, ICountry } from "src/app/models/interfaces_and_classes";


export function remapCodes(): ICountry[] {
    let _output: ICountry[] = []

    for (let oldCountry of OLD_COUNTRY_DATA){
        let _name = oldCountry['Country']
        let _capital = oldCountry['Capital']

        let _code = oldCountry['Two Letter Code']
        let _codeThree = oldCountry['Three Letter Code']
        let _continent = oldCountry['Continent']
        let _capitalLatlong =   {    
                                    latitude: oldCountry['Capital Latitude'],
                                    longitude: oldCountry['Capital Latitude']
                                }
        let _centroidLatLong = {    
                                    latitude: oldCountry['Centroid Lat'],
                                    longitude: oldCountry['Centroid Long']
                                }

        let newCountry = new Country(_name, _capital, _capitalLatlong, _centroidLatLong, _code, _codeThree, _continent)
        _output.push(newCountry)
    }

    return _output
}

export const OLD_COUNTRY_DATA: ICountryOld[] = [
    {
      "Country": "Afghanistan",
      "Capital": "Kabul",
      "Capital Latitude": 34.575503,
      "Capital Longitude": 69.240073,
      "Two Letter Code": "AF",
      "Three Letter Code": "AFG",
      "Centroid Lat": 33.93911,
      "Centroid Long": 67.709953,
      "Continent": "Asia"
    },
    {
      "Country": "Åland Islands",
      "Capital": "Mariehamn",
      "Capital Latitude": 60.1,
      "Capital Longitude": 19.933333,
      "Two Letter Code": "AX",
      "Three Letter Code": "ALA",
      "Centroid Lat": 60.1,
      "Centroid Long": 19.933333,
      "Continent": "Europe"
    },
    {
      "Country": "Albania",
      "Capital": "Tirana",
      "Capital Latitude": 41.327546,
      "Capital Longitude": 19.818698,
      "Two Letter Code": "AL",
      "Three Letter Code": "ALB",
      "Centroid Lat": 41.153332,
      "Centroid Long": 20.168331,
      "Continent": "Europe"
    },
    {
      "Country": "Algeria",
      "Capital": "Algiers",
      "Capital Latitude": 36.752887,
      "Capital Longitude": 3.042048,
      "Two Letter Code": "DZ",
      "Three Letter Code": "DZA",
      "Centroid Lat": 28.033886,
      "Centroid Long": 1.659626,
      "Continent": "Africa"
    },
    {
      "Country": "American Samoa",
      "Capital": "Pago Pago",
      "Capital Latitude": -14.275632,
      "Capital Longitude": -170.702036,
      "Two Letter Code": "AS",
      "Three Letter Code": "ASM",
      "Centroid Lat": -14.270972,
      "Centroid Long": -170.132217,
      "Continent": "Oceania"
    },
    {
      "Country": "Andorra",
      "Capital": "Andorra la Vella",
      "Capital Latitude": 42.506317,
      "Capital Longitude": 1.521835,
      "Two Letter Code": "AD",
      "Three Letter Code": "AND",
      "Centroid Lat": 42.546245,
      "Centroid Long": 1.601554,
      "Continent": "Europe"
    },
    {
      "Country": "Angola",
      "Capital": "Luanda",
      "Capital Latitude": -8.839988,
      "Capital Longitude": 13.289437,
      "Two Letter Code": "AO",
      "Three Letter Code": "AGO",
      "Centroid Lat": -11.202692,
      "Centroid Long": 17.873887,
      "Continent": "Africa"
    },
    {
      "Country": "Anguilla",
      "Capital": "The Valley",
      "Capital Latitude": 18.214813,
      "Capital Longitude": -63.057441,
      "Two Letter Code": "AI",
      "Three Letter Code": "AIA",
      "Centroid Lat": 18.220554,
      "Centroid Long": -63.068615,
      "Continent": "Americas"
    },
    {
      "Country": "Antarctica",
      "Capital": "South Pole",
      "Capital Latitude": -90,
      "Capital Longitude": 0,
      "Two Letter Code": "AQ",
      "Three Letter Code": "ATA",
      "Centroid Lat": -75.250973,
      "Centroid Long": -0.071389,
      "Continent": "Antarctica"
    },
    {
      "Country": "Antigua and Barbuda",
      "Capital": "St. John's",
      "Capital Latitude": 17.12741,
      "Capital Longitude": -61.846772,
      "Two Letter Code": "AG",
      "Three Letter Code": "ATG",
      "Centroid Lat": 17.060816,
      "Centroid Long": -61.796428,
      "Continent": "Americas"
    },
    {
      "Country": "Argentina",
      "Capital": "Buenos Aires",
      "Capital Latitude": -34.603684,
      "Capital Longitude": -58.381559,
      "Two Letter Code": "AR",
      "Three Letter Code": "ARG",
      "Centroid Lat": -38.416097,
      "Centroid Long": -63.616672,
      "Continent": "Americas"
    },
    {
      "Country": "Armenia",
      "Capital": "Yerevan",
      "Capital Latitude": 40.179186,
      "Capital Longitude": 44.499103,
      "Two Letter Code": "AM",
      "Three Letter Code": "ARM",
      "Centroid Lat": 40.069099,
      "Centroid Long": 45.038189,
      "Continent": "Asia"
    },
    {
      "Country": "Aruba",
      "Capital": "Oranjestad",
      "Capital Latitude": 12.509204,
      "Capital Longitude": -70.008631,
      "Two Letter Code": "AW",
      "Three Letter Code": "ABW",
      "Centroid Lat": 12.52111,
      "Centroid Long": -69.968338,
      "Continent": "Americas"
    },
    {
      "Country": "Australia",
      "Capital": "Canberra",
      "Capital Latitude": -35.282,
      "Capital Longitude": 149.128684,
      "Two Letter Code": "AU",
      "Three Letter Code": "AUS",
      "Centroid Lat": -25.274398,
      "Centroid Long": 133.775136,
      "Continent": "Oceania"
    },
    {
      "Country": "Austria",
      "Capital": "Vienna",
      "Capital Latitude": 48.208174,
      "Capital Longitude": 16.373819,
      "Two Letter Code": "AT",
      "Three Letter Code": "AUT",
      "Centroid Lat": 47.516231,
      "Centroid Long": 14.550072,
      "Continent": "Europe"
    },
    {
      "Country": "Azerbaijan",
      "Capital": "Baku",
      "Capital Latitude": 40.409262,
      "Capital Longitude": 49.867092,
      "Two Letter Code": "AZ",
      "Three Letter Code": "AZE",
      "Centroid Lat": 40.143105,
      "Centroid Long": 47.576927,
      "Continent": "Asia"
    },
    {
      "Country": "Bahamas",
      "Capital": "Nassau",
      "Capital Latitude": 25.047984,
      "Capital Longitude": -77.355413,
      "Two Letter Code": "BS",
      "Three Letter Code": "BHS",
      "Centroid Lat": 25.03428,
      "Centroid Long": -77.39628,
      "Continent": "Americas"
    },
    {
      "Country": "Bahrain",
      "Capital": "Manama",
      "Capital Latitude": 26.228516,
      "Capital Longitude": 50.58605,
      "Two Letter Code": "BH",
      "Three Letter Code": "BHR",
      "Centroid Lat": 25.930414,
      "Centroid Long": 50.637772,
      "Continent": "Asia"
    },
    {
      "Country": "Bangladesh",
      "Capital": "Dhaka",
      "Capital Latitude": 23.810332,
      "Capital Longitude": 90.412518,
      "Two Letter Code": "BD",
      "Three Letter Code": "BGD",
      "Centroid Lat": 23.684994,
      "Centroid Long": 90.356331,
      "Continent": "Asia"
    },
    {
      "Country": "Barbados",
      "Capital": "Bridgetown",
      "Capital Latitude": 13.113222,
      "Capital Longitude": -59.598809,
      "Two Letter Code": "BB",
      "Three Letter Code": "BRB",
      "Centroid Lat": 13.193887,
      "Centroid Long": -59.543198,
      "Continent": "Americas"
    },
    {
      "Country": "Belarus",
      "Capital": "Minsk",
      "Capital Latitude": 53.90454,
      "Capital Longitude": 27.561524,
      "Two Letter Code": "BY",
      "Three Letter Code": "BLR",
      "Centroid Lat": 53.709807,
      "Centroid Long": 27.953389,
      "Continent": "Europe"
    },
    {
      "Country": "Belgium",
      "Capital": "Brussels",
      "Capital Latitude": 50.85034,
      "Capital Longitude": 4.35171,
      "Two Letter Code": "BE",
      "Three Letter Code": "BEL",
      "Centroid Lat": 50.503887,
      "Centroid Long": 4.469936,
      "Continent": "Europe"
    },
    {
      "Country": "Belize",
      "Capital": "Belmopan",
      "Capital Latitude": 17.251011,
      "Capital Longitude": -88.75902,
      "Two Letter Code": "BZ",
      "Three Letter Code": "BLZ",
      "Centroid Lat": 17.189877,
      "Centroid Long": -88.49765,
      "Continent": "Americas"
    },
    {
      "Country": "Benin",
      "Capital": "Porto-Novo",
      "Capital Latitude": 6.496857,
      "Capital Longitude": 2.628852,
      "Two Letter Code": "BJ",
      "Three Letter Code": "BEN",
      "Centroid Lat": 9.30769,
      "Centroid Long": 2.315834,
      "Continent": "Africa"
    },
    {
      "Country": "Bermuda",
      "Capital": "Hamilton",
      "Capital Latitude": 32.294816,
      "Capital Longitude": -64.781375,
      "Two Letter Code": "BM",
      "Three Letter Code": "BMU",
      "Centroid Lat": 32.321384,
      "Centroid Long": -64.75737,
      "Continent": "Americas"
    },
    {
      "Country": "Bhutan",
      "Capital": "Thimphu",
      "Capital Latitude": 27.472792,
      "Capital Longitude": 89.639286,
      "Two Letter Code": "BT",
      "Three Letter Code": "BTN",
      "Centroid Lat": 27.514162,
      "Centroid Long": 90.433601,
      "Continent": "Asia"
    },
    {
      "Country": "Bolivia",
      "Capital": "La Paz",
      "Capital Latitude": -16.489689,
      "Capital Longitude": -68.119294,
      "Two Letter Code": "BO",
      "Three Letter Code": "BOL",
      "Centroid Lat": -16.290154,
      "Centroid Long": -63.588653,
      "Continent": "Americas"
    },
    {
      "Country": "Bosnia and Herzegovina",
      "Capital": "Sarajevo",
      "Capital Latitude": 43.856259,
      "Capital Longitude": 18.413076,
      "Two Letter Code": "BA",
      "Three Letter Code": "BIH",
      "Centroid Lat": 43.915886,
      "Centroid Long": 17.679076,
      "Continent": "Europe"
    },
    {
      "Country": "Botswana",
      "Capital": "Gaborone",
      "Capital Latitude": -24.628208,
      "Capital Longitude": 25.923147,
      "Two Letter Code": "BW",
      "Three Letter Code": "BWA",
      "Centroid Lat": -22.328474,
      "Centroid Long": 24.684866,
      "Continent": "Africa"
    },
    {
      "Country": "Bouvet Island",
      "Capital": "Bouvet Island",
      "Capital Latitude": -54.43,
      "Capital Longitude": 3.38,
      "Two Letter Code": "BV",
      "Three Letter Code": "BVT",
      "Centroid Lat": -54.423199,
      "Centroid Long": 3.413194,
      "Continent": "Atlantic Ocean"
    },
    {
      "Country": "Brazil",
      "Capital": "Brasília",
      "Capital Latitude": -15.794229,
      "Capital Longitude": -47.882166,
      "Two Letter Code": "BR",
      "Three Letter Code": "BRA",
      "Centroid Lat": -14.235004,
      "Centroid Long": -51.92528,
      "Continent": "Americas"
    },
    {
      "Country": "British Indian Ocean Territory",
      "Capital": "Camp Justice",
      "Capital Latitude": 21.3419,
      "Capital Longitude": 55.4778,
      "Two Letter Code": "IO",
      "Three Letter Code": "IOT",
      "Centroid Lat": -6.343194,
      "Centroid Long": 71.876519,
      "Continent": "Asia"
    },
    {
      "Country": "British Virgin Islands",
      "Capital": "Road Town",
      "Capital Latitude": 18.428612,
      "Capital Longitude": -64.618466,
      "Two Letter Code": "VG",
      "Three Letter Code": "VGB",
      "Centroid Lat": 18.420695,
      "Centroid Long": -64.639968,
      "Continent": "Americas"
    },
    {
      "Country": "Brunei",
      "Capital": "Bandar Seri Begawan",
      "Capital Latitude": 4.903052,
      "Capital Longitude": 114.939821,
      "Two Letter Code": "BN",
      "Three Letter Code": "BRN",
      "Centroid Lat": 4.535277,
      "Centroid Long": 114.727669,
      "Continent": "Asia"
    },
    {
      "Country": "Bulgaria",
      "Capital": "Sofia",
      "Capital Latitude": 42.697708,
      "Capital Longitude": 23.321868,
      "Two Letter Code": "BG",
      "Three Letter Code": "BGR",
      "Centroid Lat": 42.733883,
      "Centroid Long": 25.48583,
      "Continent": "Europe"
    },
    {
      "Country": "Burkina Faso",
      "Capital": "Ouagadougou",
      "Capital Latitude": 12.371428,
      "Capital Longitude": -1.51966,
      "Two Letter Code": "BF",
      "Three Letter Code": "BFA",
      "Centroid Lat": 12.238333,
      "Centroid Long": -1.561593,
      "Continent": "Africa"
    },
    {
      "Country": "Burundi",
      "Capital": "Bujumbura",
      "Capital Latitude": -3.361378,
      "Capital Longitude": 29.359878,
      "Two Letter Code": "BI",
      "Three Letter Code": "BDI",
      "Centroid Lat": -3.373056,
      "Centroid Long": 29.918886,
      "Continent": "Africa"
    },
    {
      "Country": "Cambodia",
      "Capital": "Phnom Penh",
      "Capital Latitude": 11.544873,
      "Capital Longitude": 104.892167,
      "Two Letter Code": "KH",
      "Three Letter Code": "KHM",
      "Centroid Lat": 12.565679,
      "Centroid Long": 104.990963,
      "Continent": "Asia"
    },
    {
      "Country": "Cameroon",
      "Capital": "Yaoundé",
      "Capital Latitude": 3.848033,
      "Capital Longitude": 11.502075,
      "Two Letter Code": "CM",
      "Three Letter Code": "CMR",
      "Centroid Lat": 7.369722,
      "Centroid Long": 12.354722,
      "Continent": "Africa"
    },
    {
      "Country": "Canada",
      "Capital": "Ottawa",
      "Capital Latitude": 45.42153,
      "Capital Longitude": -75.697193,
      "Two Letter Code": "CA",
      "Three Letter Code": "CAN",
      "Centroid Lat": 56.130366,
      "Centroid Long": -106.346771,
      "Continent": "Americas"
    },
    {
      "Country": "Cape Verde",
      "Capital": "Praia",
      "Capital Latitude": 14.93305,
      "Capital Longitude": -23.513327,
      "Two Letter Code": "CV",
      "Three Letter Code": "CPV",
      "Centroid Lat": 16.002082,
      "Centroid Long": -24.013197,
      "Continent": "Africa"
    },
    {
      "Country": "Cayman Islands",
      "Capital": "George Town",
      "Capital Latitude": 19.286932,
      "Capital Longitude": -81.367439,
      "Two Letter Code": "KY",
      "Three Letter Code": "CYM",
      "Centroid Lat": 19.513469,
      "Centroid Long": -80.566956,
      "Continent": "Americas"
    },
    {
      "Country": "Central African Republic",
      "Capital": "Bangui",
      "Capital Latitude": 4.394674,
      "Capital Longitude": 18.55819,
      "Two Letter Code": "CF",
      "Three Letter Code": "CAF",
      "Centroid Lat": 6.611111,
      "Centroid Long": 20.939444,
      "Continent": "Africa"
    },
    {
      "Country": "Chad",
      "Capital": "N'Djamena",
      "Capital Latitude": 12.134846,
      "Capital Longitude": 15.055742,
      "Two Letter Code": "TD",
      "Three Letter Code": "TCD",
      "Centroid Lat": 15.454166,
      "Centroid Long": 18.732207,
      "Continent": "Africa"
    },
    {
      "Country": "Chile",
      "Capital": "Santiago",
      "Capital Latitude": -33.44889,
      "Capital Longitude": -70.669265,
      "Two Letter Code": "CL",
      "Three Letter Code": "CHL",
      "Centroid Lat": -35.675147,
      "Centroid Long": -71.542969,
      "Continent": "Americas"
    },
    {
      "Country": "China",
      "Capital": "Beijing",
      "Capital Latitude": 39.904211,
      "Capital Longitude": 116.407395,
      "Two Letter Code": "CN",
      "Three Letter Code": "CHN",
      "Centroid Lat": 35.86166,
      "Centroid Long": 104.195397,
      "Continent": "Asia"
    },
    {
      "Country": "Christmas Island",
      "Capital": "Flying Fish Cove",
      "Capital Latitude": -10.420686,
      "Capital Longitude": 105.679379,
      "Two Letter Code": "CX",
      "Three Letter Code": "CXR",
      "Centroid Lat": -10.447525,
      "Centroid Long": 105.690449,
      "Continent": "Asia"
    },
    {
      "Country": "Cocos (Keeling) Islands",
      "Capital": "West Island",
      "Capital Latitude": -12.188834,
      "Capital Longitude": 96.829316,
      "Two Letter Code": "CC",
      "Three Letter Code": "CCK",
      "Centroid Lat": -12.164165,
      "Centroid Long": 96.870956,
      "Continent": "Asia"
    },
    {
      "Country": "Colombia",
      "Capital": "Bogotá",
      "Capital Latitude": 4.710989,
      "Capital Longitude": -74.072092,
      "Two Letter Code": "CO",
      "Three Letter Code": "COL",
      "Centroid Lat": 4.570868,
      "Centroid Long": -74.297333,
      "Continent": "Americas"
    },
    {
      "Country": "Comoros",
      "Capital": "Moroni",
      "Capital Latitude": -11.717216,
      "Capital Longitude": 43.247315,
      "Two Letter Code": "KM",
      "Three Letter Code": "COM",
      "Centroid Lat": -11.875001,
      "Centroid Long": 43.872219,
      "Continent": "Africa"
    },
    {
      "Country": "Congo (DRC)",
      "Capital": "Kinshasa",
      "Capital Latitude": -4.441931,
      "Capital Longitude": 15.266293,
      "Two Letter Code": "CD",
      "Three Letter Code": "COD",
      "Centroid Lat": -4.038333,
      "Centroid Long": 21.758664,
      "Continent": "Africa"
    },
    {
      "Country": "Congo (Republic)",
      "Capital": "Brazzaville",
      "Capital Latitude": -4.26336,
      "Capital Longitude": 15.242885,
      "Two Letter Code": "CG",
      "Three Letter Code": "COG",
      "Centroid Lat": -0.228021,
      "Centroid Long": 15.827659,
      "Continent": "Africa"
    },
    {
      "Country": "Cook Islands",
      "Capital": "Avarua",
      "Capital Latitude": -21.212901,
      "Capital Longitude": -159.782306,
      "Two Letter Code": "CK",
      "Three Letter Code": "COK",
      "Centroid Lat": -21.236736,
      "Centroid Long": -159.777671,
      "Continent": "Oceania"
    },
    {
      "Country": "Costa Rica",
      "Capital": "San José",
      "Capital Latitude": 9.928069,
      "Capital Longitude": -84.090725,
      "Two Letter Code": "CR",
      "Three Letter Code": "CRI",
      "Centroid Lat": 9.748917,
      "Centroid Long": -83.753428,
      "Continent": "Americas"
    },
    {
      "Country": "Côte d’Ivoire",
      "Capital": "Yamoussoukro",
      "Capital Latitude": 6.827623,
      "Capital Longitude": -5.289343,
      "Two Letter Code": "CI",
      "Three Letter Code": "CIV",
      "Centroid Lat": 7.539989,
      "Centroid Long": -5.54708,
      "Continent": "Africa"
    },
    {
      "Country": "Croatia",
      "Capital": "Zagreb ",
      "Capital Latitude": 45.815011,
      "Capital Longitude": 15.981919,
      "Two Letter Code": "HR",
      "Three Letter Code": "HRV",
      "Centroid Lat": 45.1,
      "Centroid Long": 15.2,
      "Continent": "Europe"
    },
    {
      "Country": "Cuba",
      "Capital": "Havana",
      "Capital Latitude": 23.05407,
      "Capital Longitude": -82.345189,
      "Two Letter Code": "CU",
      "Three Letter Code": "CUB",
      "Centroid Lat": 21.521757,
      "Centroid Long": -77.781167,
      "Continent": "Americas"
    },
    {
      "Country": "Curaçao",
      "Capital": "Willemstad",
      "Capital Latitude": 12.122422,
      "Capital Longitude": -68.882423,
      "Two Letter Code": "CW",
      "Three Letter Code": "CUW",
      "Centroid Lat": 12.122422,
      "Centroid Long": -68.882423,
      "Continent": "Americas"
    },
    {
      "Country": "Cyprus",
      "Capital": "Nicosia",
      "Capital Latitude": 35.185566,
      "Capital Longitude": 33.382276,
      "Two Letter Code": "CY",
      "Three Letter Code": "CYP",
      "Centroid Lat": 35.126413,
      "Centroid Long": 33.429859,
      "Continent": "Asia"
    },
    {
      "Country": "Czechia",
      "Capital": "Prague",
      "Capital Latitude": 50.075538,
      "Capital Longitude": 14.4378,
      "Two Letter Code": "CZ",
      "Three Letter Code": "CZE",
      "Centroid Lat": 49.817492,
      "Centroid Long": 15.472962,
      "Continent": "Europe"
    },
    {
      "Country": "Denmark",
      "Capital": "Copenhagen",
      "Capital Latitude": 55.676097,
      "Capital Longitude": 12.568337,
      "Two Letter Code": "DK",
      "Three Letter Code": "DNK",
      "Centroid Lat": 56.26392,
      "Centroid Long": 9.501785,
      "Continent": "Europe"
    },
    {
      "Country": "Djibouti",
      "Capital": "Djibouti",
      "Capital Latitude": 11.572077,
      "Capital Longitude": 43.145647,
      "Two Letter Code": "DJ",
      "Three Letter Code": "DJI",
      "Centroid Lat": 11.825138,
      "Centroid Long": 42.590275,
      "Continent": "Africa"
    },
    {
      "Country": "Dominica",
      "Capital": "Roseau",
      "Capital Latitude": 15.309168,
      "Capital Longitude": -61.379355,
      "Two Letter Code": "DM",
      "Three Letter Code": "DMA",
      "Centroid Lat": 15.414999,
      "Centroid Long": -61.370976,
      "Continent": "Americas"
    },
    {
      "Country": "Dominican Republic",
      "Capital": "Santo Domingo",
      "Capital Latitude": 18.486058,
      "Capital Longitude": -69.931212,
      "Two Letter Code": "DO",
      "Three Letter Code": "DOM",
      "Centroid Lat": 18.735693,
      "Centroid Long": -70.162651,
      "Continent": "Americas"
    },
    {
      "Country": "Ecuador",
      "Capital": "Quito",
      "Capital Latitude": -0.180653,
      "Capital Longitude": -78.467838,
      "Two Letter Code": "EC",
      "Three Letter Code": "ECU",
      "Centroid Lat": -1.831239,
      "Centroid Long": -78.183406,
      "Continent": "Americas"
    },
    {
      "Country": "Egypt",
      "Capital": "Cairo",
      "Capital Latitude": 30.04442,
      "Capital Longitude": 31.235712,
      "Two Letter Code": "EG",
      "Three Letter Code": "EGY",
      "Centroid Lat": 26.820553,
      "Centroid Long": 30.802498,
      "Continent": "Africa"
    },
    {
      "Country": "El Salvador",
      "Capital": "San Salvador",
      "Capital Latitude": 13.69294,
      "Capital Longitude": -89.218191,
      "Two Letter Code": "SV",
      "Three Letter Code": "SLV",
      "Centroid Lat": 13.794185,
      "Centroid Long": -88.89653,
      "Continent": "Americas"
    },
    {
      "Country": "Equatorial Guinea",
      "Capital": "Malabo",
      "Capital Latitude": 3.750412,
      "Capital Longitude": 8.737104,
      "Two Letter Code": "GQ",
      "Three Letter Code": "GNQ",
      "Centroid Lat": 1.650801,
      "Centroid Long": 10.267895,
      "Continent": "Africa"
    },
    {
      "Country": "Eritrea",
      "Capital": "Asmara",
      "Capital Latitude": 15.322877,
      "Capital Longitude": 38.925052,
      "Two Letter Code": "ER",
      "Three Letter Code": "ERI",
      "Centroid Lat": 15.179384,
      "Centroid Long": 39.782334,
      "Continent": "Africa"
    },
    {
      "Country": "Estonia",
      "Capital": "Tallinn",
      "Capital Latitude": 59.436961,
      "Capital Longitude": 24.753575,
      "Two Letter Code": "EE",
      "Three Letter Code": "EST",
      "Centroid Lat": 58.595272,
      "Centroid Long": 25.013607,
      "Continent": "Europe"
    },
    {
      "Country": "Ethiopia",
      "Capital": "Addis Ababa",
      "Capital Latitude": 8.980603,
      "Capital Longitude": 38.757761,
      "Two Letter Code": "ET",
      "Three Letter Code": "ETH",
      "Centroid Lat": 9.145,
      "Centroid Long": 40.489673,
      "Continent": "Africa"
    },
    {
      "Country": "Falkland Islands",
      "Capital": "Stanley",
      "Capital Latitude": -51.697713,
      "Capital Longitude": -57.851663,
      "Two Letter Code": "FK",
      "Three Letter Code": "FLK",
      "Centroid Lat": -51.796253,
      "Centroid Long": -59.523613,
      "Continent": "Americas"
    },
    {
      "Country": "Faroe Islands",
      "Capital": "Tórshavn",
      "Capital Latitude": 62.007864,
      "Capital Longitude": -6.790982,
      "Two Letter Code": "FO",
      "Three Letter Code": "FRO",
      "Centroid Lat": 61.892635,
      "Centroid Long": -6.911806,
      "Continent": "Europe"
    },
    {
      "Country": "Fiji",
      "Capital": "Suva",
      "Capital Latitude": -18.124809,
      "Capital Longitude": 178.450079,
      "Two Letter Code": "FJ",
      "Three Letter Code": "FJI",
      "Centroid Lat": -16.578193,
      "Centroid Long": 179.414413,
      "Continent": "Oceania"
    },
    {
      "Country": "Finland",
      "Capital": "Helsinki",
      "Capital Latitude": 60.173324,
      "Capital Longitude": 24.941025,
      "Two Letter Code": "FI",
      "Three Letter Code": "FIN",
      "Centroid Lat": 61.92411,
      "Centroid Long": 25.748151,
      "Continent": "Europe"
    },
    {
      "Country": "France",
      "Capital": "Paris",
      "Capital Latitude": 48.856614,
      "Capital Longitude": 2.352222,
      "Two Letter Code": "FR",
      "Three Letter Code": "FRA",
      "Centroid Lat": 46.227638,
      "Centroid Long": 2.213749,
      "Continent": "Europe"
    },
    {
      "Country": "French Guiana",
      "Capital": "Cayenne",
      "Capital Latitude": 4.92242,
      "Capital Longitude": -52.313453,
      "Two Letter Code": "GF",
      "Three Letter Code": "GUF",
      "Centroid Lat": 3.933889,
      "Centroid Long": -53.125782,
      "Continent": "Americas"
    },
    {
      "Country": "French Polynesia",
      "Capital": "Papeete",
      "Capital Latitude": -17.551625,
      "Capital Longitude": -149.558476,
      "Two Letter Code": "PF",
      "Three Letter Code": "PYF",
      "Centroid Lat": -17.679742,
      "Centroid Long": -149.406843,
      "Continent": "Oceania"
    },
    {
      "Country": "French Southern Territories",
      "Capital": "Saint-Pierre ",
      "Capital Latitude": -21.3419,
      "Capital Longitude": 55.4778,
      "Two Letter Code": "TF",
      "Three Letter Code": "ATF",
      "Centroid Lat": -49.280366,
      "Centroid Long": 69.348557,
      "Continent": "Indian Ocean"
    },
    {
      "Country": "Gabon",
      "Capital": "Libreville",
      "Capital Latitude": 0.416198,
      "Capital Longitude": 9.467268,
      "Two Letter Code": "GA",
      "Three Letter Code": "GAB",
      "Centroid Lat": -0.803689,
      "Centroid Long": 11.609444,
      "Continent": "Africa"
    },
    {
      "Country": "Gambia",
      "Capital": "Banjul",
      "Capital Latitude": 13.454876,
      "Capital Longitude": -16.579032,
      "Two Letter Code": "GM",
      "Three Letter Code": "GMB",
      "Centroid Lat": 13.443182,
      "Centroid Long": -15.310139,
      "Continent": "Africa"
    },
    {
      "Country": "Georgia",
      "Capital": "Tbilisi",
      "Capital Latitude": 41.715138,
      "Capital Longitude": 44.827096,
      "Two Letter Code": "GE",
      "Three Letter Code": "GEO",
      "Centroid Lat": 42.315407,
      "Centroid Long": 43.356892,
      "Continent": "Asia"
    },
    {
      "Country": "Germany",
      "Capital": "Berlin",
      "Capital Latitude": 52.520007,
      "Capital Longitude": 13.404954,
      "Two Letter Code": "DE",
      "Three Letter Code": "DEU",
      "Centroid Lat": 51.165691,
      "Centroid Long": 10.451526,
      "Continent": "Europe"
    },
    {
      "Country": "Ghana",
      "Capital": "Accra",
      "Capital Latitude": 5.603717,
      "Capital Longitude": -0.186964,
      "Two Letter Code": "GH",
      "Three Letter Code": "GHA",
      "Centroid Lat": 7.946527,
      "Centroid Long": -1.023194,
      "Continent": "Africa"
    },
    {
      "Country": "Gibraltar",
      "Capital": "Gibraltar",
      "Capital Latitude": 36.140773,
      "Capital Longitude": -5.353599,
      "Two Letter Code": "GI",
      "Three Letter Code": "GIB",
      "Centroid Lat": 36.137741,
      "Centroid Long": -5.345374,
      "Continent": "Europe"
    },
    {
      "Country": "Greece",
      "Capital": "Athens",
      "Capital Latitude": 37.983917,
      "Capital Longitude": 23.72936,
      "Two Letter Code": "GR",
      "Three Letter Code": "GRC",
      "Centroid Lat": 39.074208,
      "Centroid Long": 21.824312,
      "Continent": "Europe"
    },
    {
      "Country": "Greenland",
      "Capital": "Nuuk",
      "Capital Latitude": 64.18141,
      "Capital Longitude": -51.694138,
      "Two Letter Code": "GL",
      "Three Letter Code": "GRL",
      "Centroid Lat": 71.706936,
      "Centroid Long": -42.604303,
      "Continent": "Americas"
    },
    {
      "Country": "Grenada",
      "Capital": "St. George's",
      "Capital Latitude": 12.056098,
      "Capital Longitude": -61.7488,
      "Two Letter Code": "GD",
      "Three Letter Code": "GRD",
      "Centroid Lat": 12.262776,
      "Centroid Long": -61.604171,
      "Continent": "Americas"
    },
    {
      "Country": "Guadeloupe",
      "Capital": "Basse-Terre",
      "Capital Latitude": 16.014453,
      "Capital Longitude": -61.706411,
      "Two Letter Code": "GP",
      "Three Letter Code": "GLP",
      "Centroid Lat": 16.995971,
      "Centroid Long": -62.067641,
      "Continent": "Americas"
    },
    {
      "Country": "Guam",
      "Capital": "Hagåtña",
      "Capital Latitude": 13.470891,
      "Capital Longitude": 144.751278,
      "Two Letter Code": "GU",
      "Three Letter Code": "GUM",
      "Centroid Lat": 13.444304,
      "Centroid Long": 144.793731,
      "Continent": "Oceania"
    },
    {
      "Country": "Guatemala",
      "Capital": "Guatemala City",
      "Capital Latitude": 14.634915,
      "Capital Longitude": -90.506882,
      "Two Letter Code": "GT",
      "Three Letter Code": "GTM",
      "Centroid Lat": 15.783471,
      "Centroid Long": -90.230759,
      "Continent": "Americas"
    },
    {
      "Country": "Guernsey",
      "Capital": "St. Peter Port",
      "Capital Latitude": 49.455443,
      "Capital Longitude": -2.536871,
      "Two Letter Code": "GG",
      "Three Letter Code": "GGY",
      "Centroid Lat": 49.465691,
      "Centroid Long": -2.585278,
      "Continent": "Europe"
    },
    {
      "Country": "Guinea",
      "Capital": "Conakry",
      "Capital Latitude": 9.641185,
      "Capital Longitude": -13.578401,
      "Two Letter Code": "GN",
      "Three Letter Code": "GIN",
      "Centroid Lat": 9.945587,
      "Centroid Long": -9.696645,
      "Continent": "Africa"
    },
    {
      "Country": "Guinea-Bissau",
      "Capital": "Bissau",
      "Capital Latitude": 11.881655,
      "Capital Longitude": -15.617794,
      "Two Letter Code": "GW",
      "Three Letter Code": "GNB",
      "Centroid Lat": 11.803749,
      "Centroid Long": -15.180413,
      "Continent": "Africa"
    },
    {
      "Country": "Guyana",
      "Capital": "Georgetown",
      "Capital Latitude": 6.801279,
      "Capital Longitude": -58.155125,
      "Two Letter Code": "GY",
      "Three Letter Code": "GUY",
      "Centroid Lat": 4.860416,
      "Centroid Long": -58.93018,
      "Continent": "Americas"
    },
    {
      "Country": "Haiti",
      "Capital": "Port-au-Prince",
      "Capital Latitude": 18.594395,
      "Capital Longitude": -72.307433,
      "Two Letter Code": "HT",
      "Three Letter Code": "HTI",
      "Centroid Lat": 18.971187,
      "Centroid Long": -72.285215,
      "Continent": "Americas"
    },
    {
      "Country": "Honduras",
      "Capital": "Tegucigalpa",
      "Capital Latitude": 14.072275,
      "Capital Longitude": -87.192136,
      "Two Letter Code": "HN",
      "Three Letter Code": "HND",
      "Centroid Lat": 15.199999,
      "Centroid Long": -86.241905,
      "Continent": "Americas"
    },
    {
      "Country": "Hong Kong",
      "Capital": "Hong Kong",
      "Capital Latitude": 22.396428,
      "Capital Longitude": 114.109497,
      "Two Letter Code": "HK",
      "Three Letter Code": "HKG",
      "Centroid Lat": 22.396428,
      "Centroid Long": 114.109497,
      "Continent": "Asia"
    },
    {
      "Country": "Hungary",
      "Capital": "Budapest",
      "Capital Latitude": 47.497912,
      "Capital Longitude": 19.040235,
      "Two Letter Code": "HU",
      "Three Letter Code": "HUN",
      "Centroid Lat": 47.162494,
      "Centroid Long": 19.503304,
      "Continent": "Europe"
    },
    {
      "Country": "Iceland",
      "Capital": "Reykjavík",
      "Capital Latitude": 64.126521,
      "Capital Longitude": -21.817439,
      "Two Letter Code": "IS",
      "Three Letter Code": "ISL",
      "Centroid Lat": 64.963051,
      "Centroid Long": -19.020835,
      "Continent": "Europe"
    },
    {
      "Country": "India",
      "Capital": "New Delhi",
      "Capital Latitude": 28.613939,
      "Capital Longitude": 77.209021,
      "Two Letter Code": "IN",
      "Three Letter Code": "IND",
      "Centroid Lat": 20.593684,
      "Centroid Long": 78.96288,
      "Continent": "Asia"
    },
    {
      "Country": "Indonesia",
      "Capital": "Jakarta",
      "Capital Latitude": -6.208763,
      "Capital Longitude": 106.845599,
      "Two Letter Code": "ID",
      "Three Letter Code": "IDN",
      "Centroid Lat": -0.789275,
      "Centroid Long": 113.921327,
      "Continent": "Asia"
    },
    {
      "Country": "Iran",
      "Capital": "Tehran",
      "Capital Latitude": 35.689198,
      "Capital Longitude": 51.388974,
      "Two Letter Code": "IR",
      "Three Letter Code": "IRN",
      "Centroid Lat": 32.427908,
      "Centroid Long": 53.688046,
      "Continent": "Asia"
    },
    {
      "Country": "Iraq",
      "Capital": "Baghdad",
      "Capital Latitude": 33.312806,
      "Capital Longitude": 44.361488,
      "Two Letter Code": "IQ",
      "Three Letter Code": "IRQ",
      "Centroid Lat": 33.223191,
      "Centroid Long": 43.679291,
      "Continent": "Asia"
    },
    {
      "Country": "Ireland",
      "Capital": "Dublin",
      "Capital Latitude": 53.349805,
      "Capital Longitude": -6.26031,
      "Two Letter Code": "IE",
      "Three Letter Code": "IRL",
      "Centroid Lat": 53.41291,
      "Centroid Long": -8.24389,
      "Continent": "Europe"
    },
    {
      "Country": "Isle of Man",
      "Capital": "Douglas",
      "Capital Latitude": 54.152337,
      "Capital Longitude": -4.486123,
      "Two Letter Code": "IM",
      "Three Letter Code": "IMN",
      "Centroid Lat": 54.236107,
      "Centroid Long": -4.548056,
      "Continent": "Europe"
    },
    {
      "Country": "Israel",
      "Capital": "Tel Aviv",
      "Capital Latitude": 32.0853,
      "Capital Longitude": 34.781768,
      "Two Letter Code": "IL",
      "Three Letter Code": "ISR",
      "Centroid Lat": 31.046051,
      "Centroid Long": 34.851612,
      "Continent": "Asia"
    },
    {
      "Country": "Italy",
      "Capital": "Rome",
      "Capital Latitude": 41.902784,
      "Capital Longitude": 12.496366,
      "Two Letter Code": "IT",
      "Three Letter Code": "ITA",
      "Centroid Lat": 41.87194,
      "Centroid Long": 12.56738,
      "Continent": "Europe"
    },
    {
      "Country": "Jamaica",
      "Capital": "Kingston",
      "Capital Latitude": 18.042327,
      "Capital Longitude": -76.802893,
      "Two Letter Code": "JM",
      "Three Letter Code": "JAM",
      "Centroid Lat": 18.109581,
      "Centroid Long": -77.297508,
      "Continent": "Americas"
    },
    {
      "Country": "Japan",
      "Capital": "Tokyo",
      "Capital Latitude": 35.709026,
      "Capital Longitude": 139.731992,
      "Two Letter Code": "JP",
      "Three Letter Code": "JPN",
      "Centroid Lat": 36.204824,
      "Centroid Long": 138.252924,
      "Continent": "Asia"
    },
    {
      "Country": "Jersey",
      "Capital": "St. Helier",
      "Capital Latitude": 49.186823,
      "Capital Longitude": -2.106568,
      "Two Letter Code": "JE",
      "Three Letter Code": "JEY",
      "Centroid Lat": 49.214439,
      "Centroid Long": -2.13125,
      "Continent": "Europe"
    },
    {
      "Country": "Jordan",
      "Capital": "Amman",
      "Capital Latitude": 31.956578,
      "Capital Longitude": 35.945695,
      "Two Letter Code": "JO",
      "Three Letter Code": "JOR",
      "Centroid Lat": 30.585164,
      "Centroid Long": 36.238414,
      "Continent": "Asia"
    },
    {
      "Country": "Kazakhstan",
      "Capital": "Astana",
      "Capital Latitude": 51.160523,
      "Capital Longitude": 71.470356,
      "Two Letter Code": "KZ",
      "Three Letter Code": "KAZ",
      "Centroid Lat": 48.019573,
      "Centroid Long": 66.923684,
      "Continent": "Asia"
    },
    {
      "Country": "Kenya",
      "Capital": "Nairobi",
      "Capital Latitude": -1.292066,
      "Capital Longitude": 36.821946,
      "Two Letter Code": "KE",
      "Three Letter Code": "KEN",
      "Centroid Lat": -0.023559,
      "Centroid Long": 37.906193,
      "Continent": "Africa"
    },
    {
      "Country": "Kiribati",
      "Capital": "Tarawa Atoll",
      "Capital Latitude": 1.451817,
      "Capital Longitude": 172.971662,
      "Two Letter Code": "KI",
      "Three Letter Code": "KIR",
      "Centroid Lat": -3.370417,
      "Centroid Long": -168.734039,
      "Continent": "Oceania"
    },
    {
      "Country": "Kosovo",
      "Capital": "Pristina",
      "Capital Latitude": 42.662914,
      "Capital Longitude": 21.165503,
      "Two Letter Code": "XK",
      "Three Letter Code": "XXK",
      "Centroid Lat": 42.602636,
      "Centroid Long": 20.902977,
      "Continent": "Europe"
    },
    {
      "Country": "Kuwait",
      "Capital": "Kuwait City",
      "Capital Latitude": 29.375859,
      "Capital Longitude": 47.977405,
      "Two Letter Code": "KW",
      "Three Letter Code": "KWT",
      "Centroid Lat": 29.31166,
      "Centroid Long": 47.481766,
      "Continent": "Asia"
    },
    {
      "Country": "Kyrgyzstan",
      "Capital": "Bishkek",
      "Capital Latitude": 42.874621,
      "Capital Longitude": 74.569762,
      "Two Letter Code": "KG",
      "Three Letter Code": "KGZ",
      "Centroid Lat": 41.20438,
      "Centroid Long": 74.766098,
      "Continent": "Asia"
    },
    {
      "Country": "Laos",
      "Capital": "Vientiane",
      "Capital Latitude": 17.975706,
      "Capital Longitude": 102.633104,
      "Two Letter Code": "LA",
      "Three Letter Code": "LAO",
      "Centroid Lat": 19.85627,
      "Centroid Long": 102.495496,
      "Continent": "Asia"
    },
    {
      "Country": "Latvia",
      "Capital": "Riga",
      "Capital Latitude": 56.949649,
      "Capital Longitude": 24.105186,
      "Two Letter Code": "LV",
      "Three Letter Code": "LVA",
      "Centroid Lat": 56.879635,
      "Centroid Long": 24.603189,
      "Continent": "Europe"
    },
    {
      "Country": "Lebanon",
      "Capital": "Beirut",
      "Capital Latitude": 33.888629,
      "Capital Longitude": 35.495479,
      "Two Letter Code": "LB",
      "Three Letter Code": "LBN",
      "Centroid Lat": 33.854721,
      "Centroid Long": 35.862285,
      "Continent": "Asia"
    },
    {
      "Country": "Lesotho",
      "Capital": "Maseru",
      "Capital Latitude": -29.363219,
      "Capital Longitude": 27.51436,
      "Two Letter Code": "LS",
      "Three Letter Code": "LSO",
      "Centroid Lat": -29.609988,
      "Centroid Long": 28.233608,
      "Continent": "Africa"
    },
    {
      "Country": "Liberia",
      "Capital": "Monrovia",
      "Capital Latitude": 6.290743,
      "Capital Longitude": -10.760524,
      "Two Letter Code": "LR",
      "Three Letter Code": "LBR",
      "Centroid Lat": 6.428055,
      "Centroid Long": -9.429499,
      "Continent": "Africa"
    },
    {
      "Country": "Libya",
      "Capital": "Tripoli",
      "Capital Latitude": 32.887209,
      "Capital Longitude": 13.191338,
      "Two Letter Code": "LY",
      "Three Letter Code": "LBY",
      "Centroid Lat": 26.3351,
      "Centroid Long": 17.228331,
      "Continent": "Africa"
    },
    {
      "Country": "Liechtenstein",
      "Capital": "Vaduz",
      "Capital Latitude": 47.14103,
      "Capital Longitude": 9.520928,
      "Two Letter Code": "LI",
      "Three Letter Code": "LIE",
      "Centroid Lat": 47.166,
      "Centroid Long": 9.555373,
      "Continent": "Europe"
    },
    {
      "Country": "Lithuania",
      "Capital": "Vilnius",
      "Capital Latitude": 54.687156,
      "Capital Longitude": 25.279651,
      "Two Letter Code": "LT",
      "Three Letter Code": "LTU",
      "Centroid Lat": 55.169438,
      "Centroid Long": 23.881275,
      "Continent": "Europe"
    },
    {
      "Country": "Luxembourg",
      "Capital": "Luxembourg",
      "Capital Latitude": 49.611621,
      "Capital Longitude": 6.131935,
      "Two Letter Code": "LU",
      "Three Letter Code": "LUX",
      "Centroid Lat": 49.815273,
      "Centroid Long": 6.129583,
      "Continent": "Europe"
    },
    {
      "Country": "Macau",
      "Capital": "Macau",
      "Capital Latitude": 22.166667,
      "Capital Longitude": 113.55,
      "Two Letter Code": "MO",
      "Three Letter Code": "MAC",
      "Centroid Lat": 22.198745,
      "Centroid Long": 113.543873,
      "Continent": "Asia"
    },
    {
      "Country": "Republic of North Macedonia",
      "Capital": "Skopje",
      "Capital Latitude": 41.997346,
      "Capital Longitude": 21.427996,
      "Two Letter Code": "MK",
      "Three Letter Code": "MKD",
      "Centroid Lat": 41.608635,
      "Centroid Long": 21.745275,
      "Continent": "Europe"
    },
    {
      "Country": "Madagascar",
      "Capital": "Antananarivo",
      "Capital Latitude": -18.87919,
      "Capital Longitude": 47.507905,
      "Two Letter Code": "MG",
      "Three Letter Code": "MDG",
      "Centroid Lat": -18.766947,
      "Centroid Long": 46.869107,
      "Continent": "Africa"
    },
    {
      "Country": "Malawi",
      "Capital": "Lilongwe",
      "Capital Latitude": -13.962612,
      "Capital Longitude": 33.774119,
      "Two Letter Code": "MW",
      "Three Letter Code": "MWI",
      "Centroid Lat": -13.254308,
      "Centroid Long": 34.301525,
      "Continent": "Africa"
    },
    {
      "Country": "Malaysia",
      "Capital": "Kuala Lumpur",
      "Capital Latitude": 3.139003,
      "Capital Longitude": 101.686855,
      "Two Letter Code": "MY",
      "Three Letter Code": "MYS",
      "Centroid Lat": 4.210484,
      "Centroid Long": 101.975766,
      "Continent": "Asia"
    },
    {
      "Country": "Maldives",
      "Capital": "Malé",
      "Capital Latitude": 4.175496,
      "Capital Longitude": 73.509347,
      "Two Letter Code": "MV",
      "Three Letter Code": "MDV",
      "Centroid Lat": 3.202778,
      "Centroid Long": 73.22068,
      "Continent": "Asia"
    },
    {
      "Country": "Mali",
      "Capital": "Bamako",
      "Capital Latitude": 12.639232,
      "Capital Longitude": -8.002889,
      "Two Letter Code": "ML",
      "Three Letter Code": "MLI",
      "Centroid Lat": 17.570692,
      "Centroid Long": -3.996166,
      "Continent": "Africa"
    },
    {
      "Country": "Malta",
      "Capital": "Valletta",
      "Capital Latitude": 35.898909,
      "Capital Longitude": 14.514553,
      "Two Letter Code": "MT",
      "Three Letter Code": "MLT",
      "Centroid Lat": 35.937496,
      "Centroid Long": 14.375416,
      "Continent": "Europe"
    },
    {
      "Country": "Marshall Islands",
      "Capital": "Majuro",
      "Capital Latitude": 7.116421,
      "Capital Longitude": 171.185774,
      "Two Letter Code": "MH",
      "Three Letter Code": "MHL",
      "Centroid Lat": 7.131474,
      "Centroid Long": 171.184478,
      "Continent": "Oceania"
    },
    {
      "Country": "Martinique",
      "Capital": "Fort-de-France",
      "Capital Latitude": 14.616065,
      "Capital Longitude": -61.05878,
      "Two Letter Code": "MQ",
      "Three Letter Code": "MTQ",
      "Centroid Lat": 14.641528,
      "Centroid Long": -61.024174,
      "Continent": "Americas"
    },
    {
      "Country": "Mauritania",
      "Capital": "Nouakchott",
      "Capital Latitude": 18.07353,
      "Capital Longitude": -15.958237,
      "Two Letter Code": "MR",
      "Three Letter Code": "MRT",
      "Centroid Lat": 21.00789,
      "Centroid Long": -10.940835,
      "Continent": "Africa"
    },
    {
      "Country": "Mauritius",
      "Capital": "Port Louis",
      "Capital Latitude": -20.166896,
      "Capital Longitude": 57.502332,
      "Two Letter Code": "MU",
      "Three Letter Code": "MUS",
      "Centroid Lat": -20.348404,
      "Centroid Long": 57.552152,
      "Continent": "Africa"
    },
    {
      "Country": "Mayotte",
      "Capital": "Mamoudzou",
      "Capital Latitude": -12.780949,
      "Capital Longitude": 45.227872,
      "Two Letter Code": "YT",
      "Three Letter Code": "MYT",
      "Centroid Lat": -12.8275,
      "Centroid Long": 45.166244,
      "Continent": "Africa"
    },
    {
      "Country": "Mexico",
      "Capital": "Mexico City",
      "Capital Latitude": 19.432608,
      "Capital Longitude": -99.133208,
      "Two Letter Code": "MX",
      "Three Letter Code": "MEX",
      "Centroid Lat": 23.634501,
      "Centroid Long": -102.552784,
      "Continent": "Americas"
    },
    {
      "Country": "Micronesia",
      "Capital": "Palikir",
      "Capital Latitude": 6.914712,
      "Capital Longitude": 158.161027,
      "Two Letter Code": "FM",
      "Three Letter Code": "FSM",
      "Centroid Lat": 7.425554,
      "Centroid Long": 150.550812,
      "Continent": "Oceania"
    },
    {
      "Country": "Moldova",
      "Capital": "Chisinau",
      "Capital Latitude": 47.010453,
      "Capital Longitude": 28.86381,
      "Two Letter Code": "MD",
      "Three Letter Code": "MDA",
      "Centroid Lat": 47.411631,
      "Centroid Long": 28.369885,
      "Continent": "Europe"
    },
    {
      "Country": "Monaco",
      "Capital": "Monaco",
      "Capital Latitude": 43.737411,
      "Capital Longitude": 7.420816,
      "Two Letter Code": "MC",
      "Three Letter Code": "MCO",
      "Centroid Lat": 43.750298,
      "Centroid Long": 7.412841,
      "Continent": "Europe"
    },
    {
      "Country": "Mongolia",
      "Capital": "Ulaanbaatar",
      "Capital Latitude": 47.886399,
      "Capital Longitude": 106.905744,
      "Two Letter Code": "MN",
      "Three Letter Code": "MNG",
      "Centroid Lat": 46.862496,
      "Centroid Long": 103.846656,
      "Continent": "Asia"
    },
    {
      "Country": "Montenegro",
      "Capital": "Podgorica",
      "Capital Latitude": 42.43042,
      "Capital Longitude": 19.259364,
      "Two Letter Code": "ME",
      "Three Letter Code": "MNE",
      "Centroid Lat": 42.708678,
      "Centroid Long": 19.37439,
      "Continent": "Europe"
    },
    {
      "Country": "Montserrat",
      "Capital": "Plymouth",
      "Capital Latitude": 16.706523,
      "Capital Longitude": -62.215738,
      "Two Letter Code": "MS",
      "Three Letter Code": "MSR",
      "Centroid Lat": 16.742498,
      "Centroid Long": -62.187366,
      "Continent": "Americas"
    },
    {
      "Country": "Morocco",
      "Capital": "Rabat",
      "Capital Latitude": 33.97159,
      "Capital Longitude": -6.849813,
      "Two Letter Code": "MA",
      "Three Letter Code": "MAR",
      "Centroid Lat": 31.791702,
      "Centroid Long": -7.09262,
      "Continent": "Africa"
    },
    {
      "Country": "Mozambique",
      "Capital": "Maputo",
      "Capital Latitude": -25.891968,
      "Capital Longitude": 32.605135,
      "Two Letter Code": "MZ",
      "Three Letter Code": "MOZ",
      "Centroid Lat": -18.665695,
      "Centroid Long": 35.529562,
      "Continent": "Africa"
    },
    {
      "Country": "Myanmar",
      "Capital": "Naypyidaw",
      "Capital Latitude": 19.763306,
      "Capital Longitude": 96.07851,
      "Two Letter Code": "MM",
      "Three Letter Code": "MMR",
      "Centroid Lat": 21.913965,
      "Centroid Long": 95.956223,
      "Continent": "Asia"
    },
    {
      "Country": "Namibia",
      "Capital": "Windhoek",
      "Capital Latitude": -22.560881,
      "Capital Longitude": 17.065755,
      "Two Letter Code": "NA",
      "Three Letter Code": "NAM",
      "Centroid Lat": -22.95764,
      "Centroid Long": 18.49041,
      "Continent": "Africa"
    },
    {
      "Country": "Nauru",
      "Capital": "Yaren",
      "Capital Latitude": -0.546686,
      "Capital Longitude": 166.921091,
      "Two Letter Code": "NR",
      "Three Letter Code": "NRU",
      "Centroid Lat": -0.522778,
      "Centroid Long": 166.931503,
      "Continent": "Oceania"
    },
    {
      "Country": "Nepal",
      "Capital": "Kathmandu",
      "Capital Latitude": 27.717245,
      "Capital Longitude": 85.323961,
      "Two Letter Code": "NP",
      "Three Letter Code": "NPL",
      "Centroid Lat": 28.394857,
      "Centroid Long": 84.124008,
      "Continent": "Asia"
    },
    {
      "Country": "Netherlands",
      "Capital": "Amsterdam",
      "Capital Latitude": 52.370216,
      "Capital Longitude": 4.895168,
      "Two Letter Code": "NL",
      "Three Letter Code": "NLD",
      "Centroid Lat": 52.132633,
      "Centroid Long": 5.291266,
      "Continent": "Europe"
    },
    {
      "Country": "Netherlands Antilles",
      "Capital": "Willemstad ",
      "Capital Latitude": 12.1091242,
      "Capital Longitude": -68.9316546,
      "Two Letter Code": "AN",
      "Three Letter Code": "ANT",
      "Centroid Lat": 12.226079,
      "Centroid Long": -69.060087,
      "Continent": "Americas"
    },
    {
      "Country": "New Caledonia",
      "Capital": "Nouméa",
      "Capital Latitude": -22.255823,
      "Capital Longitude": 166.450524,
      "Two Letter Code": "NC",
      "Three Letter Code": "NCL",
      "Centroid Lat": -20.904305,
      "Centroid Long": 165.618042,
      "Continent": "Oceania"
    },
    {
      "Country": "New Zealand",
      "Capital": "Wellington",
      "Capital Latitude": -41.28646,
      "Capital Longitude": 174.776236,
      "Two Letter Code": "NZ",
      "Three Letter Code": "NZL",
      "Centroid Lat": -40.900557,
      "Centroid Long": 174.885971,
      "Continent": "Oceania"
    },
    {
      "Country": "Nicaragua",
      "Capital": "Managua",
      "Capital Latitude": 12.114993,
      "Capital Longitude": -86.236174,
      "Two Letter Code": "NI",
      "Three Letter Code": "NIC",
      "Centroid Lat": 12.865416,
      "Centroid Long": -85.207229,
      "Continent": "Americas"
    },
    {
      "Country": "Niger",
      "Capital": "Niamey",
      "Capital Latitude": 13.511596,
      "Capital Longitude": 2.125385,
      "Two Letter Code": "NE",
      "Three Letter Code": "NER",
      "Centroid Lat": 17.607789,
      "Centroid Long": 8.081666,
      "Continent": "Africa"
    },
    {
      "Country": "Nigeria",
      "Capital": "Abuja",
      "Capital Latitude": 9.076479,
      "Capital Longitude": 7.398574,
      "Two Letter Code": "NG",
      "Three Letter Code": "NGA",
      "Centroid Lat": 9.081999,
      "Centroid Long": 8.675277,
      "Continent": "Africa"
    },
    {
      "Country": "Niue",
      "Capital": "Alofi",
      "Capital Latitude": -19.055371,
      "Capital Longitude": -169.917871,
      "Two Letter Code": "NU",
      "Three Letter Code": "NIU",
      "Centroid Lat": -19.054445,
      "Centroid Long": -169.867233,
      "Continent": "Oceania"
    },
    {
      "Country": "Norfolk Island",
      "Capital": "Kingston",
      "Capital Latitude": -29.056394,
      "Capital Longitude": 167.959588,
      "Two Letter Code": "NF",
      "Three Letter Code": "NFK",
      "Centroid Lat": -29.040835,
      "Centroid Long": 167.954712,
      "Continent": "Oceania"
    },
    {
      "Country": "North Korea",
      "Capital": "Pyongyang",
      "Capital Latitude": 39.039219,
      "Capital Longitude": 125.762524,
      "Two Letter Code": "KP",
      "Three Letter Code": "PRK",
      "Centroid Lat": 40.339852,
      "Centroid Long": 127.510093,
      "Continent": "Asia"
    },
    {
      "Country": "Northern Mariana Islands",
      "Capital": "Saipan",
      "Capital Latitude": 15.177801,
      "Capital Longitude": 145.750967,
      "Two Letter Code": "MP",
      "Three Letter Code": "MNP",
      "Centroid Lat": 17.33083,
      "Centroid Long": 145.38469,
      "Continent": "Oceania"
    },
    {
      "Country": "Norway",
      "Capital": "Oslo",
      "Capital Latitude": 59.913869,
      "Capital Longitude": 10.752245,
      "Two Letter Code": "NO",
      "Three Letter Code": "NOR",
      "Centroid Lat": 60.472024,
      "Centroid Long": 8.468946,
      "Continent": "Europe"
    },
    {
      "Country": "Oman",
      "Capital": "Muscat",
      "Capital Latitude": 23.58589,
      "Capital Longitude": 58.405923,
      "Two Letter Code": "OM",
      "Three Letter Code": "OMN",
      "Centroid Lat": 21.512583,
      "Centroid Long": 55.923255,
      "Continent": "Asia"
    },
    {
      "Country": "Pakistan",
      "Capital": "Islamabad",
      "Capital Latitude": 33.729388,
      "Capital Longitude": 73.093146,
      "Two Letter Code": "PK",
      "Three Letter Code": "PAK",
      "Centroid Lat": 30.375321,
      "Centroid Long": 69.345116,
      "Continent": "Asia"
    },
    {
      "Country": "Palau",
      "Capital": "Ngerulmud",
      "Capital Latitude": 7.500384,
      "Capital Longitude": 134.624289,
      "Two Letter Code": "PW",
      "Three Letter Code": "PLW",
      "Centroid Lat": 7.51498,
      "Centroid Long": 134.58252,
      "Continent": "Oceania"
    },
    {
      "Country": "Panama",
      "Capital": "Panama City",
      "Capital Latitude": 9.101179,
      "Capital Longitude": -79.402864,
      "Two Letter Code": "PA",
      "Three Letter Code": "PAN",
      "Centroid Lat": 8.537981,
      "Centroid Long": -80.782127,
      "Continent": "Americas"
    },
    {
      "Country": "Papua New Guinea",
      "Capital": "Port Moresby",
      "Capital Latitude": -9.4438,
      "Capital Longitude": 147.180267,
      "Two Letter Code": "PG",
      "Three Letter Code": "PNG",
      "Centroid Lat": -6.314993,
      "Centroid Long": 143.95555,
      "Continent": "Oceania"
    },
    {
      "Country": "Paraguay",
      "Capital": "Asuncion",
      "Capital Latitude": -25.26374,
      "Capital Longitude": -57.575926,
      "Two Letter Code": "PY",
      "Three Letter Code": "PRY",
      "Centroid Lat": -23.442503,
      "Centroid Long": -58.443832,
      "Continent": "Americas"
    },
    {
      "Country": "Peru",
      "Capital": "Lima",
      "Capital Latitude": -12.046374,
      "Capital Longitude": -77.042793,
      "Two Letter Code": "PE",
      "Three Letter Code": "PER",
      "Centroid Lat": -9.189967,
      "Centroid Long": -75.015152,
      "Continent": "Americas"
    },
    {
      "Country": "Philippines",
      "Capital": "Manila",
      "Capital Latitude": 14.599512,
      "Capital Longitude": 120.98422,
      "Two Letter Code": "PH",
      "Three Letter Code": "PHL",
      "Centroid Lat": 12.879721,
      "Centroid Long": 121.774017,
      "Continent": "Asia"
    },
    {
      "Country": "Pitcairn Islands",
      "Capital": "Adamstown",
      "Capital Latitude": -25.06629,
      "Capital Longitude": -130.100464,
      "Two Letter Code": "PN",
      "Three Letter Code": "PCN",
      "Centroid Lat": -24.703615,
      "Centroid Long": -127.439308,
      "Continent": "Oceania"
    },
    {
      "Country": "Poland",
      "Capital": "Warsaw",
      "Capital Latitude": 52.229676,
      "Capital Longitude": 21.012229,
      "Two Letter Code": "PL",
      "Three Letter Code": "POL",
      "Centroid Lat": 51.919438,
      "Centroid Long": 19.145136,
      "Continent": "Europe"
    },
    {
      "Country": "Portugal",
      "Capital": "Lisbon",
      "Capital Latitude": 38.722252,
      "Capital Longitude": -9.139337,
      "Two Letter Code": "PT",
      "Three Letter Code": "PRT",
      "Centroid Lat": 39.399872,
      "Centroid Long": -8.224454,
      "Continent": "Europe"
    },
    {
      "Country": "Puerto Rico",
      "Capital": "San Juan",
      "Capital Latitude": 18.466334,
      "Capital Longitude": -66.105722,
      "Two Letter Code": "PR",
      "Three Letter Code": "PRI",
      "Centroid Lat": 18.220833,
      "Centroid Long": -66.590149,
      "Continent": "Americas"
    },
    {
      "Country": "Qatar",
      "Capital": "Doha",
      "Capital Latitude": 25.285447,
      "Capital Longitude": 51.53104,
      "Two Letter Code": "QA",
      "Three Letter Code": "QAT",
      "Centroid Lat": 25.354826,
      "Centroid Long": 51.183884,
      "Continent": "Asia"
    },
    {
      "Country": "Réunion",
      "Capital": "Saint-Denis",
      "Capital Latitude": -20.882057,
      "Capital Longitude": 55.450675,
      "Two Letter Code": "RE",
      "Three Letter Code": "REU",
      "Centroid Lat": -21.115141,
      "Centroid Long": 55.536384,
      "Continent": "Africa"
    },
    {
      "Country": "Romania",
      "Capital": "Bucharest",
      "Capital Latitude": 44.426767,
      "Capital Longitude": 26.102538,
      "Two Letter Code": "RO",
      "Three Letter Code": "ROU",
      "Centroid Lat": 45.943161,
      "Centroid Long": 24.96676,
      "Continent": "Europe"
    },
    {
      "Country": "Russia",
      "Capital": "Moscow",
      "Capital Latitude": 55.755826,
      "Capital Longitude": 37.6173,
      "Two Letter Code": "RU",
      "Three Letter Code": "RUS",
      "Centroid Lat": 61.52401,
      "Centroid Long": 105.318756,
      "Continent": "Asia"
    },
    {
      "Country": "Rwanda",
      "Capital": "Kigali",
      "Capital Latitude": -1.957875,
      "Capital Longitude": 30.112735,
      "Two Letter Code": "RW",
      "Three Letter Code": "RWA",
      "Centroid Lat": -1.940278,
      "Centroid Long": 29.873888,
      "Continent": "Africa"
    },
    {
      "Country": "Saint Pierre and Miquelon",
      "Capital": "St. Pierre",
      "Capital Latitude": 46.775846,
      "Capital Longitude": -56.180636,
      "Two Letter Code": "PM",
      "Three Letter Code": "SPM",
      "Centroid Lat": 46.941936,
      "Centroid Long": -56.27111,
      "Continent": "Americas"
    },
    {
      "Country": "Saint Vincent and the Grenadines",
      "Capital": "Kingstown",
      "Capital Latitude": 13.160025,
      "Capital Longitude": -61.224816,
      "Two Letter Code": "VC",
      "Three Letter Code": "VCT",
      "Centroid Lat": 12.984305,
      "Centroid Long": -61.287228,
      "Continent": "Americas"
    },
    {
      "Country": "Samoa",
      "Capital": "Apia",
      "Capital Latitude": -13.850696,
      "Capital Longitude": -171.751355,
      "Two Letter Code": "WS",
      "Three Letter Code": "WSM",
      "Centroid Lat": -13.759029,
      "Centroid Long": -172.104629,
      "Continent": "Oceania"
    },
    {
      "Country": "San Marino",
      "Capital": "San Marino",
      "Capital Latitude": 43.935591,
      "Capital Longitude": 12.447281,
      "Two Letter Code": "SM",
      "Three Letter Code": "SMR",
      "Centroid Lat": 43.94236,
      "Centroid Long": 12.457777,
      "Continent": "Europe"
    },
    {
      "Country": "São Tomé and Príncipe",
      "Capital": "São Tomé",
      "Capital Latitude": 0.330192,
      "Capital Longitude": 6.733343,
      "Two Letter Code": "ST",
      "Three Letter Code": "STP",
      "Centroid Lat": 0.18636,
      "Centroid Long": 6.613081,
      "Continent": "Africa"
    },
    {
      "Country": "Saudi Arabia",
      "Capital": "Riyadh",
      "Capital Latitude": 24.749403,
      "Capital Longitude": 46.902838,
      "Two Letter Code": "SA",
      "Three Letter Code": "SAU",
      "Centroid Lat": 23.885942,
      "Centroid Long": 45.079162,
      "Continent": "Asia"
    },
    {
      "Country": "Senegal",
      "Capital": "Dakar",
      "Capital Latitude": 14.764504,
      "Capital Longitude": -17.366029,
      "Two Letter Code": "SN",
      "Three Letter Code": "SEN",
      "Centroid Lat": 14.497401,
      "Centroid Long": -14.452362,
      "Continent": "Africa"
    },
    {
      "Country": "Serbia",
      "Capital": "Belgrade",
      "Capital Latitude": 44.786568,
      "Capital Longitude": 20.448922,
      "Two Letter Code": "RS",
      "Three Letter Code": "SRB",
      "Centroid Lat": 44.016521,
      "Centroid Long": 21.005859,
      "Continent": "Europe"
    },
    {
      "Country": "Seychelles",
      "Capital": "Victoria",
      "Capital Latitude": -4.619143,
      "Capital Longitude": 55.451315,
      "Two Letter Code": "SC",
      "Three Letter Code": "SYC",
      "Centroid Lat": -4.679574,
      "Centroid Long": 55.491977,
      "Continent": "Africa"
    },
    {
      "Country": "Sierra Leone",
      "Capital": "Freetown",
      "Capital Latitude": 8.465677,
      "Capital Longitude": -13.231722,
      "Two Letter Code": "SL",
      "Three Letter Code": "SLE",
      "Centroid Lat": 8.460555,
      "Centroid Long": -11.779889,
      "Continent": "Africa"
    },
    {
      "Country": "Singapore",
      "Capital": "Singapore",
      "Capital Latitude": 1.280095,
      "Capital Longitude": 103.850949,
      "Two Letter Code": "SG",
      "Three Letter Code": "SGP",
      "Centroid Lat": 1.352083,
      "Centroid Long": 103.819836,
      "Continent": "Asia"
    },
    {
      "Country": "Slovakia",
      "Capital": "Bratislava",
      "Capital Latitude": 48.145892,
      "Capital Longitude": 17.107137,
      "Two Letter Code": "SK",
      "Three Letter Code": "SVK",
      "Centroid Lat": 48.669026,
      "Centroid Long": 19.699024,
      "Continent": "Europe"
    },
    {
      "Country": "Slovenia",
      "Capital": "Ljubljana",
      "Capital Latitude": 46.056947,
      "Capital Longitude": 14.505751,
      "Two Letter Code": "SI",
      "Three Letter Code": "SVN",
      "Centroid Lat": 46.151241,
      "Centroid Long": 14.995463,
      "Continent": "Europe"
    },
    {
      "Country": "Solomon Islands",
      "Capital": "Honiara",
      "Capital Latitude": -9.445638,
      "Capital Longitude": 159.9729,
      "Two Letter Code": "SB",
      "Three Letter Code": "SLB",
      "Centroid Lat": -9.64571,
      "Centroid Long": 160.156194,
      "Continent": "Oceania"
    },
    {
      "Country": "Somalia",
      "Capital": "Mogadishu",
      "Capital Latitude": 2.046934,
      "Capital Longitude": 45.318162,
      "Two Letter Code": "SO",
      "Three Letter Code": "SOM",
      "Centroid Lat": 5.152149,
      "Centroid Long": 46.199616,
      "Continent": "Africa"
    },
    {
      "Country": "South Africa",
      "Capital": "Pretoria",
      "Capital Latitude": -25.747868,
      "Capital Longitude": 28.229271,
      "Two Letter Code": "ZA",
      "Three Letter Code": "ZAF",
      "Centroid Lat": -30.559482,
      "Centroid Long": 22.937506,
      "Continent": "Africa"
    },
    {
      "Country": "South Georgia and the South Sandwich Islands",
      "Capital": "King Edward Point",
      "Capital Latitude": -54.28325,
      "Capital Longitude": -36.493735,
      "Two Letter Code": "GS",
      "Three Letter Code": "SGS",
      "Centroid Lat": -54.429579,
      "Centroid Long": -36.587909,
      "Continent": "Atlantic Ocean"
    },
    {
      "Country": "South Korea",
      "Capital": "Seoul",
      "Capital Latitude": 37.566535,
      "Capital Longitude": 126.977969,
      "Two Letter Code": "KR",
      "Three Letter Code": "KOR",
      "Centroid Lat": 35.907757,
      "Centroid Long": 127.766922,
      "Continent": "Asia"
    },
    {
      "Country": "South Sudan",
      "Capital": "Juba",
      "Capital Latitude": 4.859363,
      "Capital Longitude": 31.57125,
      "Two Letter Code": "SS",
      "Three Letter Code": "SSD",
      "Centroid Lat": 4.859363,
      "Centroid Long": 31.57125,
      "Continent": "Africa"
    },
    {
      "Country": "Spain",
      "Capital": "Madrid",
      "Capital Latitude": 40.416775,
      "Capital Longitude": -3.70379,
      "Two Letter Code": "ES",
      "Three Letter Code": "ESP",
      "Centroid Lat": 40.463667,
      "Centroid Long": -3.74922,
      "Continent": "Europe"
    },
    {
      "Country": "Sri Lanka",
      "Capital": "Sri Jayawardenepura Kotte",
      "Capital Latitude": 6.89407,
      "Capital Longitude": 79.902478,
      "Two Letter Code": "LK",
      "Three Letter Code": "LKA",
      "Centroid Lat": 7.873054,
      "Centroid Long": 80.771797,
      "Continent": "Asia"
    },
    {
      "Country": "Saint Barthélemy",
      "Capital": "Gustavia",
      "Capital Latitude": 17.896435,
      "Capital Longitude": -62.852201,
      "Two Letter Code": "BL",
      "Three Letter Code": "BLM",
      "Centroid Lat": 17.896435,
      "Centroid Long": -62.852201,
      "Continent": "Americas"
    },
    {
      "Country": "Saint Kitts and Nevis",
      "Capital": "Basseterre",
      "Capital Latitude": 17.302606,
      "Capital Longitude": -62.717692,
      "Two Letter Code": "KN",
      "Three Letter Code": "KNA",
      "Centroid Lat": 17.357822,
      "Centroid Long": -62.782998,
      "Continent": "Americas"
    },
    {
      "Country": "Saint Lucia",
      "Capital": "Castries",
      "Capital Latitude": 14.010109,
      "Capital Longitude": -60.987469,
      "Two Letter Code": "LC",
      "Three Letter Code": "LCA",
      "Centroid Lat": 13.909444,
      "Centroid Long": -60.978893,
      "Continent": "Americas"
    },
    {
      "Country": "Saint Martin",
      "Capital": "Marigot",
      "Capital Latitude": 18.067519,
      "Capital Longitude": -63.082466,
      "Two Letter Code": "SX",
      "Three Letter Code": "SXM",
      "Centroid Lat": 18.067519,
      "Centroid Long": -63.082466,
      "Continent": "Americas"
    },
    {
      "Country": "Sudan",
      "Capital": "Khartoum",
      "Capital Latitude": 15.500654,
      "Capital Longitude": 32.559899,
      "Two Letter Code": "SD",
      "Three Letter Code": "SDN",
      "Centroid Lat": 12.862807,
      "Centroid Long": 30.217636,
      "Continent": "Africa"
    },
    {
      "Country": "Suriname",
      "Capital": "Paramaribo",
      "Capital Latitude": 5.852036,
      "Capital Longitude": -55.203828,
      "Two Letter Code": "SR",
      "Three Letter Code": "SUR",
      "Centroid Lat": 3.919305,
      "Centroid Long": -56.027783,
      "Continent": "Americas"
    },
    {
      "Country": "Svalbard and Jan Mayen",
      "Capital": "Longyearbyen ",
      "Capital Latitude": 78.062,
      "Capital Longitude": 22.055,
      "Two Letter Code": "SJ",
      "Three Letter Code": "SJM",
      "Centroid Lat": 77.553604,
      "Centroid Long": 23.670272,
      "Continent": "Europe"
    },
    {
      "Country": "Eswatini (Swaziland)",
      "Capital": "Mbabane",
      "Capital Latitude": -26.305448,
      "Capital Longitude": 31.136672,
      "Two Letter Code": "SZ",
      "Three Letter Code": "SWZ",
      "Centroid Lat": -26.522503,
      "Centroid Long": 31.465866,
      "Continent": "Africa"
    },
    {
      "Country": "Sweden",
      "Capital": "Stockholm",
      "Capital Latitude": 59.329323,
      "Capital Longitude": 18.068581,
      "Two Letter Code": "SE",
      "Three Letter Code": "SWE",
      "Centroid Lat": 60.128161,
      "Centroid Long": 18.643501,
      "Continent": "Europe"
    },
    {
      "Country": "Switzerland",
      "Capital": "Bern",
      "Capital Latitude": 46.947974,
      "Capital Longitude": 7.447447,
      "Two Letter Code": "CH",
      "Three Letter Code": "CHE",
      "Centroid Lat": 46.818188,
      "Centroid Long": 8.227512,
      "Continent": "Europe"
    },
    {
      "Country": "Syria",
      "Capital": "Damascus",
      "Capital Latitude": 33.513807,
      "Capital Longitude": 36.276528,
      "Two Letter Code": "SY",
      "Three Letter Code": "SYR",
      "Centroid Lat": 34.802075,
      "Centroid Long": 38.996815,
      "Continent": "Asia"
    },
    {
      "Country": "Taiwan",
      "Capital": "Taipei",
      "Capital Latitude": 25.032969,
      "Capital Longitude": 121.565418,
      "Two Letter Code": "TW",
      "Three Letter Code": "TWN",
      "Centroid Lat": 23.69781,
      "Centroid Long": 120.960515,
      "Continent": "Asia"
    },
    {
      "Country": "Tajikistan",
      "Capital": "Dushanbe",
      "Capital Latitude": 38.559772,
      "Capital Longitude": 68.787038,
      "Two Letter Code": "TJ",
      "Three Letter Code": "TJK",
      "Centroid Lat": 38.861034,
      "Centroid Long": 71.276093,
      "Continent": "Asia"
    },
    {
      "Country": "Tanzania",
      "Capital": "Dodoma",
      "Capital Latitude": -6.162959,
      "Capital Longitude": 35.751607,
      "Two Letter Code": "TZ",
      "Three Letter Code": "TZA",
      "Centroid Lat": -6.369028,
      "Centroid Long": 34.888822,
      "Continent": "Africa"
    },
    {
      "Country": "Thailand",
      "Capital": "Bangkok",
      "Capital Latitude": 13.756331,
      "Capital Longitude": 100.501765,
      "Two Letter Code": "TH",
      "Three Letter Code": "THA",
      "Centroid Lat": 15.870032,
      "Centroid Long": 100.992541,
      "Continent": "Asia"
    },
    {
      "Country": "Timor-Leste",
      "Capital": "Dili",
      "Capital Latitude": -8.556856,
      "Capital Longitude": 125.560314,
      "Two Letter Code": "TL",
      "Three Letter Code": "TLS",
      "Centroid Lat": -8.874217,
      "Centroid Long": 125.727539,
      "Continent": "Asia"
    },
    {
      "Country": "Togo",
      "Capital": "Lomé",
      "Capital Latitude": 6.172497,
      "Capital Longitude": 1.231362,
      "Two Letter Code": "TG",
      "Three Letter Code": "TGO",
      "Centroid Lat": 8.619543,
      "Centroid Long": 0.824782,
      "Continent": "Africa"
    },
    {
      "Country": "Tokelau",
      "Capital": "Nukunonu",
      "Capital Latitude": -9.2005,
      "Capital Longitude": -171.848,
      "Two Letter Code": "TK",
      "Three Letter Code": "TKL",
      "Centroid Lat": -8.967363,
      "Centroid Long": -171.855881,
      "Continent": "Oceania"
    },
    {
      "Country": "Tonga",
      "Capital": "Nuku'alofa",
      "Capital Latitude": -21.139342,
      "Capital Longitude": -175.204947,
      "Two Letter Code": "TO",
      "Three Letter Code": "TON",
      "Centroid Lat": -21.178986,
      "Centroid Long": -175.198242,
      "Continent": "Oceania"
    },
    {
      "Country": "Trinidad and Tobago",
      "Capital": "Port of Spain",
      "Capital Latitude": 10.654901,
      "Capital Longitude": -61.501926,
      "Two Letter Code": "TT",
      "Three Letter Code": "TTO",
      "Centroid Lat": 10.691803,
      "Centroid Long": -61.222503,
      "Continent": "Americas"
    },
    {
      "Country": "Tristan da Cunha",
      "Capital": "Edinburgh of the Seven Seas",
      "Capital Latitude": -37.068042,
      "Capital Longitude": -12.311315,
      "Two Letter Code": "SH",
      "Three Letter Code": "SHN",
      "Centroid Lat": -24.143474,
      "Centroid Long": -10.030696,
      "Continent": "Atlantic Ocean"
    },
    {
      "Country": "Tunisia",
      "Capital": "Tunis",
      "Capital Latitude": 36.806495,
      "Capital Longitude": 10.181532,
      "Two Letter Code": "TN",
      "Three Letter Code": "TUN",
      "Centroid Lat": 33.886917,
      "Centroid Long": 9.537499,
      "Continent": "Africa"
    },
    {
      "Country": "Turkey",
      "Capital": "Ankara",
      "Capital Latitude": 39.933364,
      "Capital Longitude": 32.859742,
      "Two Letter Code": "TR",
      "Three Letter Code": "TUR",
      "Centroid Lat": 38.963745,
      "Centroid Long": 35.243322,
      "Continent": "Asia"
    },
    {
      "Country": "Turkmenistan",
      "Capital": "Ashgabat",
      "Capital Latitude": 37.960077,
      "Capital Longitude": 58.326063,
      "Two Letter Code": "TM",
      "Three Letter Code": "TKM",
      "Centroid Lat": 38.969719,
      "Centroid Long": 59.556278,
      "Continent": "Asia"
    },
    {
      "Country": "Turks and Caicos Islands",
      "Capital": "Cockburn Town",
      "Capital Latitude": 21.467458,
      "Capital Longitude": -71.13891,
      "Two Letter Code": "TC",
      "Three Letter Code": "TCA",
      "Centroid Lat": 21.694025,
      "Centroid Long": -71.797928,
      "Continent": "Americas"
    },
    {
      "Country": "Tuvalu",
      "Capital": "Funafuti",
      "Capital Latitude": -8.520066,
      "Capital Longitude": 179.198128,
      "Two Letter Code": "TV",
      "Three Letter Code": "TUV",
      "Centroid Lat": -7.109535,
      "Centroid Long": 177.64933,
      "Continent": "Oceania"
    },
    {
      "Country": "U.S. Virgin Islands",
      "Capital": "Charlotte Amalie",
      "Capital Latitude": 18.3419,
      "Capital Longitude": -64.930701,
      "Two Letter Code": "VI",
      "Three Letter Code": "VIR",
      "Centroid Lat": 18.335765,
      "Centroid Long": -64.896335,
      "Continent": "Americas"
    },
    {
      "Country": "Uganda",
      "Capital": "Kampala",
      "Capital Latitude": 0.347596,
      "Capital Longitude": 32.58252,
      "Two Letter Code": "UG",
      "Three Letter Code": "UGA",
      "Centroid Lat": 1.373333,
      "Centroid Long": 32.290275,
      "Continent": "Africa"
    },
    {
      "Country": "Ukraine",
      "Capital": "Kyiv",
      "Capital Latitude": 50.4501,
      "Capital Longitude": 30.5234,
      "Two Letter Code": "UA",
      "Three Letter Code": "UKR",
      "Centroid Lat": 48.379433,
      "Centroid Long": 31.16558,
      "Continent": "Europe"
    },
    {
      "Country": "United Arab Emirates",
      "Capital": "Abu Dhabi",
      "Capital Latitude": 24.299174,
      "Capital Longitude": 54.697277,
      "Two Letter Code": "AE",
      "Three Letter Code": "ARE",
      "Centroid Lat": 23.424076,
      "Centroid Long": 53.847818,
      "Continent": "Asia"
    },
    {
      "Country": "United Kingdom",
      "Capital": "London",
      "Capital Latitude": 51.507351,
      "Capital Longitude": -0.127758,
      "Two Letter Code": "GB",
      "Three Letter Code": "GBR",
      "Centroid Lat": 55.378051,
      "Centroid Long": -3.435973,
      "Continent": "Europe"
    },
    {
      "Country": "United States",
      "Capital": "Washington",
      "Capital Latitude": 38.907192,
      "Capital Longitude": -77.036871,
      "Two Letter Code": "US",
      "Three Letter Code": "USA",
      "Centroid Lat": 37.09024,
      "Centroid Long": -95.712891,
      "Continent": "Americas"
    },
    {
      "Country": "Uruguay",
      "Capital": "Montevideo",
      "Capital Latitude": -34.901113,
      "Capital Longitude": -56.164531,
      "Two Letter Code": "UY",
      "Three Letter Code": "URY",
      "Centroid Lat": -32.522779,
      "Centroid Long": -55.765835,
      "Continent": "Americas"
    },
    {
      "Country": "Uzbekistan",
      "Capital": "Tashkent",
      "Capital Latitude": 41.299496,
      "Capital Longitude": 69.240073,
      "Two Letter Code": "UZ",
      "Three Letter Code": "UZB",
      "Centroid Lat": 41.377491,
      "Centroid Long": 64.585262,
      "Continent": "Asia"
    },
    {
      "Country": "Vanuatu",
      "Capital": "Port Vila",
      "Capital Latitude": -17.733251,
      "Capital Longitude": 168.327325,
      "Two Letter Code": "VU",
      "Three Letter Code": "VUT",
      "Centroid Lat": -15.376706,
      "Centroid Long": 166.959158,
      "Continent": "Oceania"
    },
    {
      "Country": "Vatican City",
      "Capital": "Vatican City",
      "Capital Latitude": 41.902179,
      "Capital Longitude": 12.453601,
      "Two Letter Code": "VA",
      "Three Letter Code": "VAT",
      "Centroid Lat": 41.902916,
      "Centroid Long": 12.453389,
      "Continent": "Europe"
    },
    {
      "Country": "Venezuela",
      "Capital": "Caracas",
      "Capital Latitude": 10.480594,
      "Capital Longitude": -66.903606,
      "Two Letter Code": "VE",
      "Three Letter Code": "VEN",
      "Centroid Lat": 6.42375,
      "Centroid Long": -66.58973,
      "Continent": "Americas"
    },
    {
      "Country": "Vietnam",
      "Capital": "Hanoi",
      "Capital Latitude": 21.027764,
      "Capital Longitude": 105.83416,
      "Two Letter Code": "VN",
      "Three Letter Code": "VNM",
      "Centroid Lat": 14.058324,
      "Centroid Long": 108.277199,
      "Continent": "Asia"
    },
    {
      "Country": "Wallis and Futuna",
      "Capital": "Mata-Utu",
      "Capital Latitude": -13.282509,
      "Capital Longitude": -176.176447,
      "Two Letter Code": "WF",
      "Three Letter Code": "WLF",
      "Centroid Lat": -13.768752,
      "Centroid Long": -177.156097,
      "Continent": "Oceania"
    },
    {
      "Country": "Western Sahara",
      "Capital": "El Aaiún",
      "Capital Latitude": 27.125287,
      "Capital Longitude": -13.1625,
      "Two Letter Code": "EH",
      "Three Letter Code": "ESH",
      "Centroid Lat": 24.215527,
      "Centroid Long": -12.885834,
      "Continent": "Africa"
    },
    {
      "Country": "Yemen",
      "Capital": "Sana'a",
      "Capital Latitude": 15.369445,
      "Capital Longitude": 44.191007,
      "Two Letter Code": "YE",
      "Three Letter Code": "YEM",
      "Centroid Lat": 15.552727,
      "Centroid Long": 48.516388,
      "Continent": "Asia"
    },
    {
      "Country": "Zambia",
      "Capital": "Lusaka",
      "Capital Latitude": -15.387526,
      "Capital Longitude": 28.322817,
      "Two Letter Code": "ZM",
      "Three Letter Code": "ZMB",
      "Centroid Lat": -13.133897,
      "Centroid Long": 27.849332,
      "Continent": "Africa"
    },
    {
      "Country": "Zimbabwe",
      "Capital": "Harare",
      "Capital Latitude": -17.825166,
      "Capital Longitude": 31.03351,
      "Two Letter Code": "ZW",
      "Three Letter Code": "ZWE",
      "Centroid Lat": -19.015438,
      "Centroid Long": 29.154857,
      "Continent": "Africa"
    }
   ]